USE [master]
GO

/****** Object:  Database [LatamBook]    Script Date: 7/8/2015 6:07:03 PM ******/
CREATE DATABASE [LatamBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LatamBook', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LatamBook.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LatamBook_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LatamBook_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LatamBook] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LatamBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LatamBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LatamBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LatamBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LatamBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LatamBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [LatamBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LatamBook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LatamBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LatamBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LatamBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LatamBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LatamBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LatamBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LatamBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LatamBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LatamBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LatamBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LatamBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LatamBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LatamBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LatamBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LatamBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LatamBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LatamBook] SET RECOVERY FULL 
GO

ALTER DATABASE [LatamBook] SET  MULTI_USER 
GO

ALTER DATABASE [LatamBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LatamBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LatamBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LatamBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LatamBook] SET  READ_WRITE 
GO

